name: module
description: "A new Flutter module project."
version: 1.0.0+1

resolution: workspace
environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  
  package_a:
    hosted: https://my-pub.com
    version: 0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.module
    iosBundleIdentifier: com.example.module
